/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/delivery-add`; params?: Router.UnknownInputParams; } | { pathname: `/delivery-edit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/data` | `/data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/expenses` | `/expenses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/expenses/add`; params?: Router.UnknownInputParams; } | { pathname: `/expenses/categories`; params?: Router.UnknownInputParams; } | { pathname: `/expenses/edit`; params?: Router.UnknownInputParams; } | { pathname: `/projects/add`; params?: Router.UnknownInputParams; } | { pathname: `/projects/detail`; params?: Router.UnknownInputParams; } | { pathname: `/projects/edit`; params?: Router.UnknownInputParams; } | { pathname: `/transactions/add`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/delivery-add`; params?: Router.UnknownOutputParams; } | { pathname: `/delivery-edit`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/data` | `/data`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/expenses` | `/expenses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/expenses/add`; params?: Router.UnknownOutputParams; } | { pathname: `/expenses/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/expenses/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/projects/add`; params?: Router.UnknownOutputParams; } | { pathname: `/projects/detail`; params?: Router.UnknownOutputParams; } | { pathname: `/projects/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/transactions/add`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/delivery-add${`?${string}` | `#${string}` | ''}` | `/delivery-edit${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/data${`?${string}` | `#${string}` | ''}` | `/data${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/expenses${`?${string}` | `#${string}` | ''}` | `/expenses${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | `/expenses/add${`?${string}` | `#${string}` | ''}` | `/expenses/categories${`?${string}` | `#${string}` | ''}` | `/expenses/edit${`?${string}` | `#${string}` | ''}` | `/projects/add${`?${string}` | `#${string}` | ''}` | `/projects/detail${`?${string}` | `#${string}` | ''}` | `/projects/edit${`?${string}` | `#${string}` | ''}` | `/transactions/add${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/delivery-add`; params?: Router.UnknownInputParams; } | { pathname: `/delivery-edit`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/data` | `/data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/expenses` | `/expenses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/expenses/add`; params?: Router.UnknownInputParams; } | { pathname: `/expenses/categories`; params?: Router.UnknownInputParams; } | { pathname: `/expenses/edit`; params?: Router.UnknownInputParams; } | { pathname: `/projects/add`; params?: Router.UnknownInputParams; } | { pathname: `/projects/detail`; params?: Router.UnknownInputParams; } | { pathname: `/projects/edit`; params?: Router.UnknownInputParams; } | { pathname: `/transactions/add`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
